# Generated by Django 4.0.5 on 2022-06-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=5000)),
                ('instructions', models.CharField(max_length=5000)),
                ('serving_size', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('date_added', models.CharField(max_length=100)),
                ('date_modified', models.CharField(max_length=100)),
            ],
        ),
    ]
