# Generated by Django 4.0.5 on 2022-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_projectpy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
    ]
